### list estudantes
GET http://localhost:3000/estudante

### get estudante
GET http://localhost:3000/estudante/1

### create estudante
POST http://localhost:3000/estudante
Content-Type: application/json

{
    "nome": "Filipi",

    "matricula": "UC22201204",

    "email": "Aluno@gmail.com",

    "dataNascimento": "2005-04-04",

    "cidadeId": 4
}
### update estudante
PATCH  http://localhost:3000/estudante/1
Content-Type: application/json

{
    "email": "EmailAlterado@gmail.com",
}

### delete estudante
DELETE http://localhost:3000/estudante/1