### list ufs
GET http://localhost:3000/uf

### get uf
GET http://localhost:3000/uf/1

### create uf
POST http://localhost:3000/uf
Content-Type: application/json

{
    "nome":"Mato-Grosso",
    "sigla":"MG"
}

### update uf
PATCH  http://localhost:3000/uf/2
{
    "nome":"Mato-Grosso",
}

### delete uf
DELETE http://localhost:3000/uf/2